import { useEffect, useState } from 'react';
import axios from 'axios';

const API = (import.meta.env.VITE_API_URL || '/api').replace(/\/$/, '');
const emptyForm = { name: '', email: '', phone: '', jobId: '', resume: null };

function Layout({ children, navigate }) {
  return <><header><div className="nav inner"><button className="brand" onClick={() => navigate('home')}>AI Resume <span>Analyzer</span></button><nav><button onClick={() => navigate('analyze')}>Analyze Resume</button><button onClick={() => navigate('admin')}>HR Login</button></nav></div></header><main className="inner">{children}</main><footer>AI Resume Analyzer <span>College project | Simple, explainable matching</span></footer></>;
}

function Home({ navigate }) {
  return <section className="hero"><div className="eyebrow">RESUME INTELLIGENCE</div><h1>Find out how ready your resume is for the next role.</h1>
  <p>Upload a PDF, add a job description, and get a clear skill match report powered by keyword analysis and helpful AI explanations.</p>
  <button className="primary" onClick={() => navigate('analyze')}>Analyze my resume <b>→</b></button>
  <div className="hero-note"><span>✓</span> Private by design: we store extracted text, not the uploaded file.</div>
  </section>;
}

function Analyzer({ navigate, setResult }) {
  const [form, setForm] = useState(emptyForm); const [loading, setLoading] = useState(false); 
  const [error, setError] = useState('');
  const [jobs, setJobs] = useState([]);
  useEffect(() => { axios.get(`${API}/jobs`).then(response => setJobs(response.data)).catch(() => setError('Could not load available jobs.')); }, []);
  const update = event => setForm({ ...form, [event.target.name]: event.target.type === 'file' ? event.target.files[0] : event.target.value });
  const submit = async event => { event.preventDefault(); setError(''); setLoading(true);
  const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key, value || '')); try { const response = await axios.post(`${API}/analyze`, data); setResult(response.data); navigate('results'); } catch (requestError) { setError(requestError.response?.data?.message || 'Could not analyze the resume. Is the server running?'); } finally { setLoading(false); } };
  return <section className="form-page"><div className="eyebrow">ANALYZE RESUME</div><h1>Match your experience to an opportunity.</h1><p className="lead">Select a job and the system will compare your resume with its saved requirements.</p><form onSubmit={submit} className="panel"><div className="form-grid"><label>Candidate name<input name="name" value={form.name} onChange={update} placeholder="e.g. your name" required /></label><label>Email address<input type="email" name="email" value={form.email} onChange={update} placeholder="you@example.com" required /></label><label>Phone <small>(optional)</small><input name="phone" value={form.phone} onChange={update} placeholder="+91 98765 43210" /></label><label>Resume PDF<input type="file" name="resume" onChange={update} accept="application/pdf,.pdf" required /></label></div><label>Choose job<select name="jobId" value={form.jobId} onChange={update} required><option value="">Select a job</option>{jobs.map(job => <option key={job.id} value={job.id}>{job.title}</option>)}</select></label>{error && <div className="error">{error}</div>}<button className="primary" disabled={loading || !jobs.length}>{loading ? 'Analyzing...' : 'Analyze Resume'} <b>→</b></button></form></section>;
}

function List({ title, items, tone }) { return <div className="list-block"><h3>{title}</h3><div className={tone || ''}>{items?.length ? items.map((item, index) => <span className="tag" key={`${item}-${index}`}>{item}</span>) : <span className="muted">None found</span>}</div></div>; }
function Results({ result, navigate }) {
  if (!result) return <section className="empty"><h1>No analysis yet</h1>
  <button className="primary" onClick={() => navigate('analyze')}>Start analysis</button></section>;
  return <section className="results"><button className="back" onClick={() => navigate('analyze')}>← New analysis</button>
  <div className="result-heading"><div>
  <div className="eyebrow">ANALYSIS REPORT</div><h1>{result.name}</h1>
  <p>{result.email} {result.phone && `· ${result.phone}`}</p></div><div className="score"><strong>{result.matchScore}%</strong><span>Match score</span></div></div><div className="score-bar"><i style={{ width: `${result.matchScore}%` }} /></div><div className="result-grid"><div className="panel"><List title="Matching skills" items={result.matchingSkills} tone="good" /><List title="Missing skills" items={result.missingSkills} tone="missing" /></div><div className="panel"><List title="Resume strengths" items={result.strengths} /><List title="Resume weaknesses" items={result.weaknesses} /><List title="Suggestions" items={result.suggestions} /></div></div></section>;
}

function Admin({ navigate }) { const [login, setLogin] = useState({ username: '', password: '' }); const [error, setError] = useState(''); const submit = async event => { event.preventDefault(); try { await axios.post(`${API}/admin/login`, login); navigate('dashboard'); } catch { setError('Invalid admin username or password.'); } }; return <section className="login"><div className="eyebrow">HR ACCESS</div><h1>Welcome back.</h1><p className="lead">Sign in to review submitted resume analyses.</p><form className="panel" onSubmit={submit}><label>Username<input value={login.username} onChange={e => setLogin({ ...login, username: e.target.value })} required /></label><label>Password<input type="password" value={login.password} onChange={e => setLogin({ ...login, password: e.target.value })} required /></label>{error && <div className="error">{error}</div>}<button className="primary">Open dashboard <b>→</b></button></form><p className="hint">Demo credentials are configured in the server .env file.</p></section>; }

function Dashboard({ navigate, setCandidate }) { const [candidates, setCandidates] = useState([]); const [error, setError] = useState(''); useEffect(() => { axios.get(`${API}/candidates`).then(response => setCandidates(response.data)).catch(() => setError('Could not load candidates. Check that the server is running.')); }, []); const sorted = [...candidates].sort((a, b) => b.matchScore - a.matchScore); return <section className="dashboard"><div className="result-heading"><div><div className="eyebrow">HR DASHBOARD</div><h1>Candidate submissions</h1><p>{candidates.length} resume analyses</p></div><button className="back" onClick={() => navigate('home')}>Sign out</button></div>{error && <div className="error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Match score</th><th>Date</th><th></th></tr></thead><tbody>{sorted.map(candidate => <tr key={candidate._id}><td><strong>{candidate.name}</strong></td><td>{candidate.email}</td><td><span className="table-score">{candidate.matchScore}%</span></td><td>{new Date(candidate.createdAt).toLocaleDateString()}</td><td><button className="view" onClick={async () => { const response = await axios.get(`${API}/candidates/${candidate._id}`); setCandidate(response.data); navigate('details'); }}>View details →</button></td></tr>)}</tbody></table>{!candidates.length && !error && <p className="muted table-empty">No submissions yet.</p>}</div></section>; }
function Details({ candidate, navigate }) { if (!candidate) return null; return <section className="results"><button className="back" onClick={() => navigate('dashboard')}>← All candidates</button><div className="result-heading"><div><div className="eyebrow">CANDIDATE DETAILS</div><h1>{candidate.name}</h1><p>{candidate.email} {candidate.phone && `· ${candidate.phone}`}</p></div><div className="score"><strong>{candidate.matchScore}%</strong><span>Match score</span></div></div><div className="detail-meta"><span><b>Resume</b>{candidate.resumeFileName}</span><span><b>Analyzed</b>{new Date(candidate.createdAt).toLocaleString()}</span></div><div className="result-grid"><div className="panel"><List title="Matching skills" items={candidate.matchingSkills} tone="good" /><List title="Missing skills" items={candidate.missingSkills} tone="missing" /></div><div className="panel"><List title="Resume strengths" items={candidate.strengths} /><List title="Resume weaknesses" items={candidate.weaknesses} /><List title="Suggestions" items={candidate.suggestions} /></div></div><div className="panel job"><h3>Job description</h3><p>{candidate.jobDescription}</p></div></section>; }

export default function App() { const [page, setPage] = useState('home'); const [result, setResult] = useState(null); const [candidate, setCandidate] = useState(null); const navigate = setPage; let content = page === 'home' ? <Home navigate={navigate} /> : page === 'analyze' ? <Analyzer navigate={navigate} setResult={setResult} /> : page === 'results' ? <Results result={result} navigate={navigate} /> : page === 'admin' ? <Admin navigate={navigate} /> : page === 'dashboard' ? <Dashboard navigate={navigate} setCandidate={setCandidate} /> : <Details candidate={candidate} navigate={navigate} />; return <Layout navigate={navigate}>{content}</Layout>; }
